version: '3'
services:
  node-app:
    image: "node:8"
    volumes:
      - ./:/app
    env_file: .env
    working_dir: /app
    command: ["npm", "run", "start"]
    container_name: payment_server
    ports:
      - "3000:3000"
  mysql:
    image: mysql:5.6.33
    container_name: payment_mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    volumes:
      - "./db_data:/var/lib/mysql"
    ports:
      - "3306:3306"
  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    command: redis-server --requirepass payment123!!
    hostname: redis
    container_name: payment_redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
